language: python
python:
    - "nightly"
    - 3.5
    - 3.6
sudo: false
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true 
  allow_failures:
    - python: "nightly"
install:
    - pip install --upgrade pip
    - pip install https://github.com/hyperspy/link_traits/archive/master.zip
    - pip install https://github.com/francisco-dlp/hyperspy/archive/RELEASE_v1.4.zip
    - pip install .[test]
    - export MPLBACKEND=agg
    - pip install pytest-cov codecov --upgrade
script:
    - py.test --cov=hyperspy_gui_ipywidgets -v --pyargs hyperspy_gui_ipywidgets
after_success:
    - codecov

